---
- name: Confirm Oracle Express Pre-requisites ready
  hosts: ambari
  serial: 10
  remote_user: root
  tasks:
  - debug: var=ansible_eth0
  - name: Install components necessary for Oracle 11g Express
    yum: name={{ item.name }} state=latest
    with_items:
    - { name: 'wget'}
    - { name: 'glibc'}
    - { name: 'make'}
    - { name: 'binutils'}
    - { name: 'libaio'}
    - { name: 'libselinux-python'}
    - { name: 'bc'}
    - { name: 'flex'}
    - { name: 'unixODBC'}
  - name: Set kernel parameters
    sysctl: name={{ item.name }} value={{ item.value }}
    with_items:
     - {name: 'kernel.sem', value: '250 32000 100 128' }
     - {name: 'fs.file-max', value: '6815744' }



- name: Copy Oracle express, unzip and commence silent installation
  hosts: ambari
  serial: 10
  remote_user: root
  vars:
    oracleExpress: oracle-xe-11.2.0-1.0.x86_64
    oracleExpressResponse: OracleExpress.rsp
  tasks:
  - name: Copy the Oracle Express from the disk image directory
    unarchive: copy=yes src=disk_images/{{ oracleExpress }}.rpm.zip dest=/
  - name: Prepare response file template
    template: src={{ oracleExpressResponse }} dest=/
  - name: make certain we are starting out fresh
    yum: name={{ oracleExpress }} state=absent
  - name: RPM install of Oracle Express
    yum: name=/Disk1/{{ oracleExpress }}.rpm 
#    command: "rpm -ivh Disk1/{{ oracleExpress }} > xeRPMInstall.log"
#  - name: Run silent Oracle Express configuration 
#   command: "/etc/init.d/oracle-xe configure responseFIle={{ oracleExpressResponse }} > XEsilentinstall.log"
