---
- name: Configure Oracle as the metastore for Ambari-Server
  hosts: ambari
  serial: 10
  remote_user: root
  vars:
    AmbariUser: admin
    AmbariPassword: admin
    OracleAdmin: SYSTEM
    OraclePassword: Hadoop
    HIVEUSER: hive
    HIVEPASSWORD: hive
    OOZIEUSER: oozie
    OOZIEPASSWORD: oozie
    AmbariSchemaScript: ~/createAmbariUser.sql
    OozieSchemaScript: ~/createOozieUser.sql
  tasks:
#  - name: Copy the .jar file to the Java share directory
#    copy: src=/u01/app/oracle/product/11.2.0/xe/jdbc/lib/ojdbc6.jar dest=/usr/share/java mode=0644
  - name: create the Ambari - Oracle ambari user creation script via template
    template: src=defineOracleUser.j2 dest={{ AmbariSchemaScript }} 
  - name: run the Ambari user creation script
    command: "sqlplus {{ OracleAdmin }}/{{ OraclePassword }} < {{ AmbariSchemaScript }}"
  - name: Define the Hive user with Oracle
    template: src=defineHiveOracleUser.j2 dest={{ HiveSchemaScript }} 
  - name: Define the Oozie user with Oracle
    template: src=DefineOozieOracleUser.j2 dest={{ OozieSchemaScript }} 
  - name: Erase prior Ambari /var/log files
    file: path=/var/log/ambari-server state=absent
  - name: Perform Ambari Oracle Setup
    command: "ambari-server setup --jdbc-db=oracle --jdbc-driver=/usr/share/java/ojdbc6.jar"

    
