    # password created with: python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
---
- hosts: all
  serial: 10
  remote_user: root
  vars:
#    ambariRepo: http://public-repo-1.hortonworks.com/ambari/centos6/2.x/updates/2.0.2/ambari.repo
     ambariRepo: http://public-repo-1.hortonworks.com/ambari/centos6/2.x/updates/2.1.2.1
#    ambariRepo: http://public-repo-1.hortonworks.com/ambari/centos6/2.x/updates/2.0.1/ambari.repo
#    yumrepo: name=ambari baseurl={{ ambariRepo }} state=present  enabled=yes gpgcheck=yes gpgcakey=http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.2.6.0/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins
  tasks:
  - name: Set the Ambari repo 
    shell: "wget -nv {{ ambariRepo }}/ambari.repo -O /etc/yum.repos.d/ambari.repo"
    register: ambariRepositoryInstalled

  - stat: path=/etc/yum.repos.d/ambari.repo
    register: st

  - fail: msg="ambari.repo not present in /etc/yum.repos.d"
    when: st.stat.exists == False

  - name: Install the Ambari agent
    yum: name=ambari-agent state=present
    when: ambariRepositoryInstalled|success

  - name: Stop iptables
    service: name=iptables state=stopped enabled=no
  - name: Disable selinux
    selinux: state=disabled 
  - name: Ensure that NTP is up and running
    service: name=ntpd state=started enabled=yes
  - name: Ensure that NTP is up and running
    service: name=ntpd state=started enabled=yes
  - name: write the standard server host file
    template:
      src: hosts.j2
      dest: /etc/hosts
  - name: Turn off transparent huge pages
    shell: "echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled"

      
- hosts: ambari
  remote_user: root 
  tasks: 
#  - name: Verify YUM repolist
#    command: "yum repolist"
   
  - name: Install ambari server
    yum: name=ambari-server 



    
#  - name: Setup ambari-server with defaults
#    shell: "ambari-server setup -s"
#
#  - name: startup ambari-server
#    shell: "sleep 10 && ambari-server start"
