    # password created with: python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
---
- hosts: all
  serial: 10
  remote_user: root
  tasks:
  - name: Add HDP Ambari assumed components
    yum: name={{item.name}} state=latest
    with_items:
    - { name: 'wget'}
    - { name: 'unzip'}
    - { name: 'yum-utils'}
    - { name: 'createrepo'}
    - { name: 'yum-plugin-priorities'}
    - { name: 'git'}
    - { name: 'ntp'} 
    - { name: 'ntpdate'} 
    - { name: 'ntp-doc'} 
    - { name: 'libselinux-python'}    

  - name: Stop iptables
    service: name=iptables state=stopped enabled=no
  - name: Disable selinux
    selinux: state=disabled 
  - name: Ensure that NTP is up and running
    service: name=ntpd state=started enabled=yes
  - name: Ensure that NTP is up and running
    service: name=ntpd state=started enabled=yes
  - name: write the standard server host file
    template:
      src: hosts.j2
      dest: /etc/hosts
  - name: Turn off transparent huge pages
    command: "echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled"
      
      
- hosts: oracle
  remote_user: root
  vars:
    hdpRepo: http://public-repo-1.hortonworks.com/ambari/centos6/1.x/updates/1.6.1/ambari.repo
#    hdpRepo: http://public-repo-1.hortonworks.com/ambari/centos6/2.x/updates/2.0.1/ambari.repo
  tasks:
  - name: Setup up Ambari repository
    command: "wget -nv {{ hdpRepo }} -O /etc/yum.repos.d/ambari.repo"
  - name: Verify YUM repolist
    command: "yum repolist"
  - name: Install ambari server
    yum: name=ambari-server 
    
#  - name: Setup ambari-server with defaults
#    command: "ambari-server setup -s"

#  - name: startup ambari-server
#    command: "ambari-server start"
      

      


      
    
        
        
        


