---
- hosts: all
  name: Remove HDP installed packages
  serial: 10
  remote_user: root
  vars:
    # password created with: python -c 'import crypt; print crypt.crypt(This is my Password, $1$SomeSalt$)'

  tasks:
#  - name: stop ambari-agents
#    command: "ambari-agent stop"
#  - name: stop ambari-server
#    command: "ambari-server stop"
  - name: YUM remove items from list
    yum: name={{item.name}} state=absent
    with_items:
    - { name: 'libconfuse' }
    - { name: 'rrdtool' }
    - { name: 'nagios-devel' }
    - { name: 'nagios-www' }
    - { name: 'nagios' }
    - { name: 'webhcat-tar-pig' }
    - { name: 'webhcat-tar-hive' }
    - { name: 'hcatalog'}    
    - { name: 'hive'}
    - { name: 'hive-hcatalog'}
    - { name: 'phoenix'}
    - { name: 'hbase'}
    - { name: 'zookeeper'}
    - { name: 'oozie'}
    - { name: 'pig'}
    - { name: 'knox'}
    - { name: 'snappy'}
    - { name: 'storm'}
    - { name: 'kafka'}
    - { name: 'ranger'}
    - { name: 'flume'}
    - { name: 'sqoop'}
    - { name: 'hadoop-lzo'}
    - { name: 'falcon'}
    - { name: 'accumulo'}              
    - { name: 'hadoop'}
    - { name: 'mysql-connector'}
    - { name: 'mysql-libs'}
    - { name: 'slider'}
    - { name: 'postgresql'}
    - { name: 'ambari-log4j'}
    - { name: 'ambari-metrics'}
    - { name: 'ambari-agent'}
    - { name: 'ambari-server'}
    - { name: 'bigtop'}
    - { name: 'hdp-select'}
    - { name: 'bigtop-jsvc'}
    - { name: 'mysql'}
    - { name: 'ganglia-devel'}
    - { name: 'ganglia-devel'}
    - { name: 'ganglia-web'}
    - { name: 'ganglia-gmetad'}
    - { name: 'libganglia'}
    - { name: 'ganglia-devel'}
    - { name: 'postgresql-libs'}
    - { name: 'ambari-server'}
    - { name: 'ambari-agent'}


- hosts: all
  name: Remove all HDP related files
  remote_user: root
  tasks:
  - name: Erase all of the /usr/lib HDP related files
    file: path={{item.path}} state=absent
    with_items:
    - { path: '/usr/lib/sqoop'}
    - { path: '/usr/lib/hive-hcatalog'}
    - { path: '/usr/lib/falcon'}
    - { path: '/usr/lib/hadoop'}
    - { path: '/usr/lib/flume'}
    - { path: '/usr/lib/storm'}
    - { path: '/usr/lib/hive'}
    - { path: '/usr/lib/oozie'}
    - { path: '/usr/lib/hadoop-hdfs'}
    - { path: '/usr/lib/knox'}
    - { path: '/usr/lib/ambari-agent'}
    - { path: '/usr/lib/ambari-server'}
    - { path: '/usr/lib/pgsql'}
    - { path: '/usr/lib/zookeeper'}
    - { path: '/usr/lib/nagios'}

  - name: Erase all of the /var/lib HDP related files
    file: path={{item.path}} state=absent
    with_items:
    - { path: '/var/lib/oozie' }
    - { path: '/var/lib/zookeeper' }
    - { path: '/var/lib/hadoop-hdfs' }
    - { path: '/var/lib/ganglia' }
    - { path: '/var/lib/hdfs' }
    - { path: '/var/lib/falcon' }

  - name: Erase all of the /etc HDP related files
    file: path={{item.path}} state=absent
    with_items:
    - { path: '/etc/nagios' }
    - { path: '/etc/hadoop'}
    - { path: '/etc/hbase '}   
    - { path: '/etc/hive'}
    - { path: '/etc/hive-webhcat'}
    - { path: '/etc/flume'}
    - { path: '/etc/falcon'}
    - { path: '/etc/ambari-metrics-monitor '}
    - { path: '/etc/hadoop-httpfs'}
    - { path: '/etc/oozie'}
    - { path: '/etc/storm '}
    - { path: '/etc/storm-slider-client'}
    - { path: '/etc/tez '}
    - { path: '/etc/ambari-agent'}
    - { path: '/etc/ambari-server'}
    - { path: '/etc/kafka'}
    - { path: '/etc/knox'}
    - { path: '/etc/phoenix'}
    - { path: '/etc/sqoop'}
    - { path: '/etc/zookeeper'}
    - { path: '/etc/hive-hcatalog'}
    - { path: '/etc/slider'}
    - { path: '/etc/ambari.repo.bak'}
    - { path: '/etc/ganglia'} 
    - { path: '/etc/yum.repos.d/HDP.repo'}
    - { path: '/etc/yum.repos.d/HDP-UTILS.repo'}   
    - { path: '/etc/yum.repos.d/ambari.repo'}
  - name: Erase all of the /var/run HDP related files
    file: path={{item.path}} state=absent
    with_items:
    - { path: '/var/run/nagios' }
    - { path: '/var/run/hadoop'}
    - { path: '/var/run/hbase '}
    - { path: '/var/run/zookeeper'}
    - { path: '/var/run/flume'}
    - { path: '/var/run/webhcat'}
    - { path: '/var/run/hadoop-yarn'}
    - { path: '/var/run/hadoop-mapreduce'}
    - { path: '/var/run/knox'}
    - { path: '/var/run/kafka'}
    - { path: '/var/run/ambari-server'}
    - { path: '/var/run/ganglia'}
    - { path: '/var/run/storm'}
    - { path: '/var/run/hive'}
    - { path: '/var/run/oozie'}
    - { path: '/var/run/falcon'}
  - name: Erase all of the /var/log HDP related files
    file: path={{item.path}} state=absent
    with_items:
    - { path: '/var/log/nagios' }                   
    - { path: '/var/log/hadoop'}
    - { path: '/var/log/hbase'}
    - { path: '/var/log/zookeeper'}
    - { path: '/var/log/flume'}
    - { path: '/var/log/storm'}
    - { path: '/var/log/hadoop-yarn'}    
    - { path: '/var/log/hadoop-mapreduce'}   
    - { path: '/var/log/knox'}
    - { path: '/var/log/kafka'}
    - { path: '/var/log/ambari-server'}
    - { path: '/var/log/ambari-agent'}
    - { path: '/var/log/hive'}
    - { path: '/var/log/oozie'}
    - { path: '/var/log/falcon'}
    - { path: '/var/log/webhcat'}
  - name: Erase all of the /var HDP related files
    file: path={{item.path}} state=absent
    with_items:
    - { path: '/var/nagios' } 
    - { path: '/var/tmp/oozie' }     
  - name: Erase all of the /tmp HDP related files
    file: path={{item.path}} state=absent
    with_items:
    - { path: '/tmp/hive' } 
    - { path: '/tmp/ambari-qa'}       
    - { path: '/tmp/sqoop-ambari-qa'}
    - { path: '/tmp/hadoop-hdfs'}
    - { path: '/hadoop/hbase'}
    - { path: '/usr/hdp/2.2.6.0-2800'}
    - { path: '/usr/hdp'}
    - { path: '/hadoop'}
    - { path: '/usr/jdk64'}
    - { path: '/var/lib/ambari-server'}
    - { path: '/etc/ambari-server'}
    - { path: '/etc/postgresql'}
    - { path: '/etc/rcd/rc3.d/S95ambari-server'}
    - { path: '/etc/rcd/rc5.d/S95ambari-server'}
    - { path: '/etc/rcd/rc1.d/S95ambari-server'}
    - { path: '/etc/rcd/rc2.d/S95ambari-server'}
    - { path: '/etc/rcd/rc4.d/S95ambari-server'}
    - { path: '/etc/rcd/rc0.d/K20ambari-server'}
    - { path: '/etc/rcd/rc1.d/K20ambari-server'}
    - { path: '/etc/rcd/rc2.d/K20ambari-server'}
    - { path: '/etc/rcd/rc6.d/K20ambari-server'}
  - name: Remove HDP Users
    user: name={{item.name}} state=absent remove=yes
    with_items:
    - { name: 'ambari-qa' }
    - { name: 'hbase' }
    - { name: 'nagios' }
    - { name: 'oozie' }
    - { name: 'hcat' }
    - { name: 'hive' }
    - { name: 'yarn' }
    - { name: 'hdfs' }
    - { name: 'mapred' }
    - { name: 'zookeeper' }
    - { name: 'rrdcached' }
    - { name: 'sqoop' }

  - name: clean slate so time to reboot
    command: "reboot now"

  
    

    
    
    
                            